In [1]:
#1.1
print("boolean表示布尔类型，float表示浮点型，int表示整数型数据")

boolean表示布尔类型，float表示浮点型，int表示整数型数据


In [2]:
#1.2
def s(n):
    if n==1:
        return 1
    elif n%2==1:
        return s(n-1)+n
    else:
        return s(n-1)-n

print(s(99))       

50


In [3]:
#1.3
s="yoyo"
list(s)

['y', 'o', 'y', 'o']

In [4]:
#2.1
'''
range(1,100)指的是1到99的连续整数: 1,2,3，...，98,99
range(1,100)[2::3]即从上述整数中索引号为2（即整数3）开始步长为3的整数列：3,6,9，...，96,99
range(1,100)[2::3][-10:]即从上述整数取最后十个： 72,75,78，...，96,99
'''
for i in range(1,100)[2::3][-10:]:
    print(i)

72
75
78
81
84
87
90
93
96
99


In [5]:
#2.2
class Stock():
    def __init__(self,time,high,low):
        self.time=time
        self.high=high
        self.low=low
    def cal_diff(self):
        diff=self.high - self.low
        return {self.time + "_diff" : diff}

one=Stock("one",15,7)
two=Stock("two",66,20)
print(one.cal_diff())
print(two.cal_diff())

{'one_diff': 8}
{'two_diff': 46}


In [6]:
#3.1
#假设df是pandas数据框
#df.columns查看列名
#df.T数据框转置

In [7]:
#3.2
import pandas as pd
import talib as ta
df=pd.read_excel("sz50.xlsx",sheet_name="600029.XSHG",index_col=0)
close=df.close.values
print(type(close))
ema=ta.EMA(close, timeperiod=10)
print(ema[-5:])

<class 'numpy.ndarray'>
[15.08227205 15.2564044  15.44433088 15.72172526 15.96322976]


In [8]:
#3.3
stocks=['600029.XSHG','600050.XSHG','601318.XSHG']
dic={stock:pd.read_excel("sz50.xlsx",sheet_name=stock,index_col=0) for stock in stocks}
pdata=pd.Panel(dic)
pdata

C:\Python\lib\site-packages\IPython\core\interactiveshell.py:2961: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 215 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume

In [9]:
#3.4
import numpy as np
arr=np.array(pdata)
print(arr.shape)
print(arr[:,-20:,0])

(3, 215, 5)
[[ 13.85  13.82  13.83  14.11  14.25  14.39  15.1   15.15  15.22  14.97
   14.89  14.99  14.71  15.07  15.35  16.    16.04  16.29  16.97  17.05]
 [  8.53   8.56   8.62   8.88   9.25   9.24   9.43   9.25   9.02   9.15
    9.63   9.5    9.9    9.97   9.96   9.49   9.68   9.61   9.63   9.8 ]
 [134.83 134.56 137.5  143.18 143.48 144.15 143.61 143.65 144.35 143.36
  146.41 144.71 148.56 156.53 157.12 157.72 154.99 163.52 168.58 169.57]]


In [10]:
#3.5
arr=np.arange(25).reshape(5,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
